import { Cupcake } from "@/types/cupcake";

// Initial data
export const cupcakes: Cupcake[] = [
  {
    id: 1,
    name: "Chocolate",
    image: "/images/cupcakes/cupcake_1.jpg",
    featured: true,
    new: true,
    favorite: false,
    price: 12.9,
    description:
      "Delicioso cupcake de chocolate com recheio cremoso e cobertura de ganache. Perfeito para os amantes de chocolate.",
    ingredients: [
      "Farinha de trigo",
      "Cacau em pó",
      "Açúcar",
      "Ovos",
      "Manteiga",
      "Leite",
      "Chocolate meio amargo",
      "Creme de leite",
    ],
    rating: 4.8,
  },
  {
    id: 2,
    name: "Morango",
    image: "/images/cupcakes/cupcake_2.jpg",
    featured: false,
    new: true,
    favorite: false,
    price: 13.9,
    description:
      "Cupcake suave com pedaços de morango fresco e cobertura de chantilly. Uma explosão de sabor frutado.",
    ingredients: [
      "Farinha de trigo",
      "Açúcar",
      "Ovos",
      "Manteiga",
      "Leite",
      "Morangos frescos",
      "Chantilly",
      "Corante alimentício rosa",
    ],
    rating: 4.5,
  },
  {
    id: 3,
    name: "Baunilha",
    image: "/images/cupcakes/cupcake_3.jpg",
    featured: true,
    new: false,
    favorite: false,
    price: 11.9,
    description:
      "Cupcake clássico de baunilha com cobertura de buttercream. Simplesmente delicioso e versátil.",
    ingredients: [
      "Farinha de trigo",
      "Açúcar",
      "Ovos",
      "Manteiga",
      "Leite",
      "Extrato de baunilha",
      "Buttercream",
      "Confeitos coloridos",
    ],
    rating: 4.7,
  },
  {
    id: 4,
    name: "Limão",
    image: "/images/cupcakes/cupcake_4.jpg",
    featured: false,
    new: false,
    favorite: false,
    price: 12.9,
    description:
      "Cupcake cítrico de limão com recheio de creme de limão e cobertura de merengue. Refrescante e saboroso.",
    ingredients: [
      "Farinha de trigo",
      "Açúcar",
      "Ovos",
      "Manteiga",
      "Leite",
      "Limão",
      "Creme de limão",
      "Merengue",
    ],
    rating: 4.6,
  },
  {
    id: 5,
    name: "Café",
    image: "/images/cupcakes/cupcake_1.jpg",
    featured: false,
    new: true,
    favorite: false,
    price: 13.9,
    description:
      "Cupcake de café com recheio de creme de café e cobertura de chocolate. Perfeito para os amantes de café.",
    ingredients: [
      "Farinha de trigo",
      "Açúcar",
      "Ovos",
      "Manteiga",
      "Leite",
      "Café expresso",
      "Creme de café",
      "Chocolate",
    ],
    rating: 4.9,
  },
  {
    id: 6,
    name: "Coco",
    image: "/images/cupcakes/cupcake_2.jpg",
    featured: true,
    new: false,
    favorite: false,
    price: 12.9,
    description:
      "Cupcake de coco com recheio de creme de coco e cobertura de coco ralado. Tropical e delicioso.",
    ingredients: [
      "Farinha de trigo",
      "Açúcar",
      "Ovos",
      "Manteiga",
      "Leite de coco",
      "Coco ralado",
      "Creme de coco",
      "Raspas de limão",
    ],
    rating: 4.4,
  },
  {
    id: 7,
    name: "Caramelo",
    image: "/images/cupcakes/cupcake_3.jpg",
    featured: false,
    new: true,
    favorite: false,
    price: 13.9,
    description:
      "Cupcake de caramelo com recheio de doce de leite e cobertura de caramelo. Doce e irresistível.",
    ingredients: [
      "Farinha de trigo",
      "Açúcar",
      "Ovos",
      "Manteiga",
      "Leite",
      "Caramelo",
      "Doce de leite",
      "Nozes",
    ],
    rating: 4.7,
  },
  {
    id: 8,
    name: "Nutella",
    image: "/images/cupcakes/cupcake_4.jpg",
    featured: true,
    new: false,
    favorite: false,
    price: 14.9,
    description:
      "Cupcake de Nutella com recheio cremoso e cobertura de Nutella. Uma delícia para os amantes de chocolate e avelã.",
    ingredients: [
      "Farinha de trigo",
      "Açúcar",
      "Ovos",
      "Manteiga",
      "Leite",
      "Nutella",
      "Creme de avelã",
      "Avelãs",
    ],
    rating: 4.9,
  },
  {
    id: 9,
    name: "Red Velvet",
    image: "/images/cupcakes/cupcake_1.jpg",
    featured: false,
    new: false,
    favorite: false,
    price: 13.9,
    description:
      "Cupcake Red Velvet com recheio de cream cheese e cobertura de buttercream. Clássico e elegante.",
    ingredients: [
      "Farinha de trigo",
      "Açúcar",
      "Ovos",
      "Manteiga",
      "Leite",
      "Cacau em pó",
      "Cream cheese",
      "Corante alimentício vermelho",
    ],
    rating: 4.8,
  },
  {
    id: 10,
    name: "Maracujá",
    image: "/images/cupcakes/cupcake_2.jpg",
    featured: true,
    new: true,
    favorite: false,
    price: 13.9,
    description:
      "Cupcake de maracujá com recheio de creme de maracujá e cobertura de merengue. Refrescante e tropical.",
    ingredients: [
      "Farinha de trigo",
      "Açúcar",
      "Ovos",
      "Manteiga",
      "Leite",
      "Maracujá",
      "Creme de maracujá",
      "Merengue",
    ],
    rating: 4.6,
  },
];
